"""Tests for editing the open Pages document (targeted formatting changes).

AppleScript (`_osa`) is stubbed, so these run offline. The key safety property — that
we only ever write the whitelisted size/font/color attributes and NEVER a `bold`
property (which corrupts Pages text) — is asserted explicitly.
"""
from __future__ import annotations

import pytest

import jarvis.tools.pages_editor as pe
from jarvis.tools.pages_editor import PagesEditError, PagesEditor, _rgb


def _patch(monkeypatch, paras):
    """Stub _osa: return the joined paragraphs for the read call, record writes."""
    scripts: list[str] = []
    joined = pe._PARA_DELIM.join(paras)

    def fake(script: str, timeout: int = 20) -> str:
        scripts.append(script)
        if "paragraphs of body text" in script and "text item delimiters" in script:
            return joined
        if "name of front document" in script:
            return "MyDoc"
        return ""

    monkeypatch.setattr(pe, "_osa", fake)
    return scripts


def test_read_paragraphs_splits_on_delimiter(monkeypatch):
    _patch(monkeypatch, ["Heading", "Body one.", "Body two."])
    assert PagesEditor().read_paragraphs() == ["Heading", "Body one.", "Body two."]


def test_active_document_name(monkeypatch):
    _patch(monkeypatch, ["x"])
    assert PagesEditor().active_document() == "MyDoc"


def test_format_paragraph_writes_only_safe_attributes(monkeypatch):
    scripts = _patch(monkeypatch, ["Heading", "Body"])
    PagesEditor().format_paragraph(1, size=32, color="dark blue")
    writes = [s for s in scripts if "set " in s]
    joined = "\n".join(writes)
    assert "set size of paragraph 1 of body text of front document to 32" in joined
    assert "set color of paragraph 1 of body text of front document to {10000, 20000, 45000}" in joined
    # NEVER a bold/italic property (that corrupts Pages text)
    assert "set bold" not in joined and "set italic" not in joined


def test_bold_maps_to_font_variant(monkeypatch):
    scripts = _patch(monkeypatch, ["Heading"])
    PagesEditor().format_paragraph(1, bold=True)
    assert any('set font of paragraph 1 of body text of front document to "Helvetica Neue Bold"' in s
               for s in scripts)


def test_bold_uses_given_family(monkeypatch):
    scripts = _patch(monkeypatch, ["Heading"])
    PagesEditor().format_paragraph(1, font="Georgia", bold=True, italic=True)
    assert any('to "Georgia Bold Italic"' in s for s in scripts)


def test_format_paragraph_out_of_range_raises(monkeypatch):
    _patch(monkeypatch, ["only one"])
    with pytest.raises(PagesEditError):
        PagesEditor().format_paragraph(5, size=20)


def test_format_all_targets_whole_body(monkeypatch):
    scripts = _patch(monkeypatch, ["a", "b"])
    PagesEditor().format_all(size=12, font="Georgia")
    joined = "\n".join(scripts)
    assert "set size of body text of front document to 12" in joined
    assert 'set font of body text of front document to "Georgia"' in joined


def test_reformat_classifies_title_heading_body(monkeypatch):
    # p1 = title (first), p2 = heading (short, no punctuation), p3 = body (a sentence)
    scripts = _patch(monkeypatch, ["Deepfakes", "How They Work",
                                   "They are synthetic media generated by AI models."])
    msg = PagesEditor().reformat(title_size=26, heading_size=17, body_size=12)
    joined = "\n".join(scripts)
    assert "set size of paragraph 1 of body text of front document to 26" in joined  # title
    assert "set size of paragraph 2 of body text of front document to 17" in joined  # heading
    assert "set size of paragraph 3 of body text of front document to 12" in joined  # body
    assert "1 title" in msg and "body paragraph" in msg


def test_reformat_empty_doc_raises(monkeypatch):
    _patch(monkeypatch, [])
    with pytest.raises(PagesEditError):
        PagesEditor().reformat()


def test_rgb_parses_names_and_hex():
    assert _rgb("dark blue") == (10000, 20000, 45000)
    assert _rgb("#ffffff") == (65535, 65535, 65535)
    assert _rgb("#000") == (0, 0, 0)
    assert _rgb("not-a-color") is None
    assert _rgb("") is None
