#!/usr/bin/env python3
"""Live end-to-end demo / manual test: build a real Pages document on *deepfakes*
using Pages' REAL built-in paragraph styles (Title / Subtitle / Heading / Body).

This mirrors what JARVIS's `create_pages_document` voice tool does: it composes the
document as a Word ``.docx`` with named styles, safely downloads relevant web images
(`SafeImageFetcher`: allowlisted trusted sources, size + magic-byte checks), adds a
table, and opens the finished document in Pages — where the styles show up as
genuine Pages Title/Heading/Body in the Format picker (not faked bold text).

Not part of the automated suite (needs the network + opens a GUI app). Run by hand:

    .venv/bin/python scripts/demo_deepfakes_pages.py
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from jarvis.config import config
from jarvis.tools.images import ImageError, SafeImageFetcher
from jarvis.tools.pages_author import PagesAuthor


def main() -> int:
    images = SafeImageFetcher(
        download_dir=config.image_download_dir,
        allowed_hosts=config.image_allowed_hosts,
        max_bytes=config.image_max_bytes,
    )

    def image_block(query: str, caption: str = "") -> dict | None:
        """Safely fetch a web image and return an image block (or None if none safe)."""
        try:
            path, res = images.fetch_one(query)
            print(f"   ✓ fetched “{res.title}” for {query!r}")
            time.sleep(1.0)  # be polite to the image host between fetches
            return {"type": "image", "path": path, "caption": caption or res.title}
        except ImageError as e:
            print(f"   ⚠ no safe image for {query!r}: {e}")
            return None

    print("Composing the 'Deepfakes' document (real Pages styles)…")
    blocks: list[dict] = [
        {"type": "heading", "text": "What Are Deepfakes?", "level": 1},
        {"type": "body", "text":
            "Deepfakes are synthetic images, video, or audio in which a person's "
            "likeness or voice is convincingly replaced or generated by artificial "
            "intelligence. The term blends \"deep learning\" and \"fake\". Modern "
            "deepfakes are produced with generative neural networks and can be very "
            "difficult to distinguish from authentic media."},
    ]
    if (b := image_block("deepfake", "An AI-generated deepfake image")):
        blocks.append(b)

    blocks += [
        {"type": "heading", "text": "How Deepfakes Are Made", "level": 1},
        {"type": "body", "text":
            "Most deepfakes are created using generative adversarial networks (GANs). "
            "A GAN pits two networks against each other: a generator that produces "
            "fakes and a discriminator that tries to tell fakes from real examples. "
            "Through repeated competition the generator learns to fool the "
            "discriminator, producing increasingly realistic output."},
    ]
    if (b := image_block("generative adversarial network diagram", "A GAN architecture diagram")):
        blocks.append(b)

    blocks += [
        {"type": "heading", "text": "Detection and Risks", "level": 1},
        {"type": "body", "text":
            "Detection relies on spotting subtle artefacts and on AI classifiers "
            "trained on known fakes. Common tell-tale signals are summarised below."},
        {"type": "table", "rows": [
            ["Signal", "What to look for"],
            ["Blinking", "Irregular or absent eye blinks"],
            ["Lighting", "Shadows that don't match the scene"],
            ["Audio sync", "Lips slightly out of step with speech"],
            ["Edges", "Blurring or warping around the face"],
        ]},
    ]

    author = PagesAuthor()
    out = str(Path.home() / "Documents" / "JARVIS Deepfakes")
    print("Building the .docx with real named styles…")
    docx_path = author.create_document(
        [{"type": "title", "text": "Deepfakes"},
         {"type": "subtitle", "text": "An Overview"}] + blocks,
        out,
    )
    print(f"   wrote {docx_path}")
    print("Opening it in Pages…")
    author.open_in_pages(docx_path)

    print("\n✅ Done — 'Deepfakes' is open in Pages with real Title/Heading/Body styles.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
